# Quick scientific Python introduction

This notebook does a "whirlwind tour" of the functionality that the scientific Python stack exposes.


## Numpy

In [3]:
import numpy as np

`numpy` is one of the core scientific libraries used in Python.

The main object that it introduces is an "array" type. This array type allows for users to represent vectors, matrices, and higher dimensional arrays.

Below we create a 1-dimensional, 2-dimensional, and 3-dimensional array.

In [5]:
x = np.array([0.0, 1.0, 2.0])
y = np.array([[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]])
z = np.array([
    [[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]],
    [[6.0, 7.0], [8.0, 9.0], [10.0, 11.0]],
    [[12.0, 13.0], [14.0, 15.0], [16.0, 17.0]],
    [[18.0, 19.0], [20.0, 21.0], [22.0, 23.0]]
])

### Shapes of arrays

As we create and manipulate arrays, we will often be interested in "what shape is our current array" and "what shape do we need this array to be".

**1-dimensional**

In the code above, we created `x` by doing

```python
x = np.array([0.0, 1.0, 2.0])
```

If we asked for `len([0.0, 1.0, 2.0])` we would have seen 3 -- The 1-dimensional array in our example was size 3.

**2-dimensional**

In the code, above we created `y` by doing

```python
y = np.array([[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]])
```

Again, if we asked for `len([[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]])`, we would have received 3.

But now, there's an additional list inside! The `len([[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]][0])` would be `len([0.0, 1.0])` which is 2.

Thus our array is size 3 x 2.

The sizes correspond to the length of the lists creating them -- The inner-most dimension size is the outer-most length.

**3-dimensional**

Your turn! What size do you think `z` is?

Hint: You can check your answer by doing `z.shape`

**Indexing**

We can select elements out of the array by indexing into the arrays

In [8]:
# Python indexing starts at 0
x[0]

0.0

In [9]:
# Can select all of a particular dimension by using :
y[:, 1]

array([1., 3., 5.])

In [11]:
# One index argument per dimension
z[:, 1:3, 0]

array([[ 2.,  4.],
       [ 8., 10.],
       [14., 16.],
       [20., 22.]])

### Special array creation methods

**Create an empty array**

In [14]:
np.empty((5, 2))

array([[4.72941232e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [6.56290858e-310, 1.61900097e-051],
       [3.27042818e+179, 5.45006386e-090],
       [2.51563590e+180, 6.56295119e-310]])

**Create an array filled with zeros**

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array filled with ones**

In [17]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Create a vector filled with numbers from i to n**

In [18]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

**Create a vector filled with n evenly spaced numbers from x to z**

In [23]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

**Create a vector filled with U(0, 1)**

In [25]:
np.random.rand(2, 3)

array([[0.29644541, 0.22748884, 0.61203776],
       [0.40171583, 0.310857  , 0.5147153 ]])

**Create a vector filled with N(0, 1)**

In [27]:
np.random.randn(2, 2, 3)

array([[[-0.46765354, -0.81274839, -0.96405956],
        [ 0.76608746, -0.32705555, -0.00127782]],

       [[-0.45388651, -1.1714269 ,  0.70465237],
        [-1.03042092, -0.74393472, -0.83350862]]])

### Broadcasting

You often will need to add scalars or other arrays to arrays. We call this broadcasting.

**Operations between scalars and arrays**

These operations do mostly what you would expect -- They apply the scalar operation to each individual element of the array.

For example `z = x + 1` returns a new array, `z`, where `z_i = x_i + 1`

In [29]:
x

array([0., 1., 2.])

In [30]:
x + 1

array([1., 2., 3.])

In [31]:
x * 3

array([0., 3., 6.])

In [32]:
x - 3

array([-3., -2., -1.])

**Operations between two arrays of the same size**

Most operations do elementwise computation when you do operations on two arrays of the same size.

In [37]:
# Elementwise addition
np.ones_like(x) + x

array([1., 2., 3.])

In [40]:
# Elementwise multiplication
np.zeros_like(z) * z

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [41]:
# Dot product -- Generally will try matrix multiplication
# but for two vectors, this will just do the dot product
np.ones_like(x) @ x

3.0

**Operations between two arrays of different sizes**

You should be more careful if you are working with arrays of different sizes:

* Let `x = N x 1` and `y = N x M`) -> Then `x ? y` applies the function as if it were applying it to each column. For example, `z = x + y` gives you `z.shape => N x M` where `z[i, j] = x[i] + y[i, j]` (generalizes to higher dimensions...).
* Let `x = N x M` and `y = M x P` then `x @ y` does matrix multiplication

In [36]:
# x[:, None] is a fancy way to convert a vector into an Nx1 array
x[:, None] + y

array([[0., 1.],
       [3., 4.],
       [6., 7.]])

In [45]:
# Matrix multiplication
y @ y.T

array([[ 1.,  3.,  5.],
       [ 3., 13., 23.],
       [ 5., 23., 41.]])

### Numpy array functions

We are often interested in computing various functions of a single array -- Something like `sum` or `mean`.

`numpy` has many array functions built in. Many of these functions are something known as a "reduction" -- This just means it takes many inputs and returns a single output (think about what computing the mean does). Reductions can often be applied either to the entire array or to a single axis. If you apply it to a single axis, that axis will get collapsed into a single value.

Here we demonstrate a few of the most common array functions and some reductions:

In [48]:
# Cumulative sum
np.cumsum(x)

array([0., 1., 3.])

In [53]:
# One element differences
np.diff(x)

array([1., 1.])

In [49]:
# Mean (vector)
np.mean(x)

1.0

In [50]:
# Mean (matrix)
np.mean(y)

2.5

In [51]:
# Mean on a matrix but collapsing the rows
# y is size (3, 2) and np.mean(y, axis=0) is size (2,)
np.mean(y, axis=0)

array([2., 3.])

In [52]:
# Standard deviation on a 3 dimensional array collapsing on the
# 3rd dimension
np.std(z, axis=2)

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

### Universal functions

One of the powerful tools that `numpy` opens to users is "universal functions" (ufuncs).

These are functions that operate directly on n-dimensional arrays in an element-by-element fashion.

Not only does this make it simple to apply a function to an entire array but, behind the scenes, there is a significant amount of optimization and multithreading happening. There are lots of ufuncs available to you in `numpy` -- Take a peek at [the documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html?highlight=ufunc#available-ufuncs) for a list

In [46]:
# Computes sin(x) for each element of x
np.sin(x)

array([0.        , 0.84147098, 0.90929743])

In [47]:
np.exp(x)

array([1.        , 2.71828183, 7.3890561 ])

## Scipy

### Interpolation

### Linear algebra

### Statistics

## Matplotlib

### Figure/Axis

### More

## Numba